version: cd
services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    networks:
      - default
      - service-proxy
    ports:
      - "${POSTGRES_SERVER_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_SERVER_HOST}
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    labels:
      description: "Postgresql Database"
      service: "postgresql"
  fastapi:
    container_name: fastapi_container
    image: backend-task
    command: [ "uvicorn", "app.main:app","--host", "0.0.0.0","--reload" ]
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - default
      - service-proxy
    restart: unless-stopped
    depends_on:
      - postgres
networks:
  service-proxy:
volumes:
  postgres: