"""initial

Revision ID: 4d403b4c9088
Revises: 
Create Date: 2023-04-18 10:43:18.205919

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4d403b4c9088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('full_name', sa.String(length=64), nullable=False),
                    sa.Column('scientometric_database', sa.Enum('scopus', 'wos', 'risc', name='scientometric_status'),
                              nullable=False),
                    sa.Column('document_count', sa.Integer(), server_default='0', nullable=True),
                    sa.Column('citation_count', sa.Integer(), server_default='0', nullable=True),
                    sa.Column('h_index', sa.Integer(), server_default='0', nullable=True),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('full_name')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
