"""add_created_at_in_model

Revision ID: 87c9517cf8c7
Revises: 41e87100a92e
Create Date: 2023-04-18 21:40:39.537542

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '87c9517cf8c7'
down_revision = '41e87100a92e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.Integer(), server_default=sa.text('EXTRACT(epoch FROM now())'),
                                     nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
